{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.3.9/kotlinx-coroutines-core-1.3.9.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xt6ws6s5kffb5gn4f5ktpx2rkm"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.3.9.jar",
          "url": "kotlinx-coroutines-core-jvm-1.3.9.jar",
          "size": 1668476,
          "sha512": "cf86f567b1c53194527a18c6d1396709a53d5acb82c00c73db673805f91d1069e2ba22141b9b2425159f2788c5ca0509da425a4ab2244cc934fe4136e8c25489",
          "sha256": "6538f458473a42b6e2a92676f00d70d4fa0f6ae824d13c1e31c8051c196d2335",
          "sha1": "4be434f5e86c1998a273e7f19a7286440894f0b0",
          "md5": "e0eee49b27ade47745f6ed21caa1cd2a"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.3.9.jar",
          "url": "kotlinx-coroutines-core-jvm-1.3.9.jar",
          "size": 1668476,
          "sha512": "cf86f567b1c53194527a18c6d1396709a53d5acb82c00c73db673805f91d1069e2ba22141b9b2425159f2788c5ca0509da425a4ab2244cc934fe4136e8c25489",
          "sha256": "6538f458473a42b6e2a92676f00d70d4fa0f6ae824d13c1e31c8051c196d2335",
          "sha1": "4be434f5e86c1998a273e7f19a7286440894f0b0",
          "md5": "e0eee49b27ade47745f6ed21caa1cd2a"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-metadata/1.3.9/kotlinx-coroutines-core-metadata-1.3.9.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-metadata",
        "version": "1.3.9"
      }
    },
    {
      "name": "metadata-commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-metadata/1.3.9/kotlinx-coroutines-core-metadata-1.3.9.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-metadata",
        "version": "1.3.9"
      }
    }
  ]
}
