{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media",
    "module": "media",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6992079"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-1.2.1.aar",
          "url": "media-1.2.1.aar",
          "size": 319167,
          "sha512": "e1e4a99b161b894472ba3c7d173ea6d365f3c8d5c706a5a059a374703342e3878fbc4b4f764677d1aff15d3963902dd3194b336e8f2b0e4c60b81c7e92169055",
          "sha256": "e8726018fc4c486d79f33a5cf3c6cc8cfebbe64fef4396fc2743c20235b8118f",
          "sha1": "0f71815550fb7420ce2297d7115cea5310e70d8a",
          "md5": "f29a161718328c9ed03c575085e12a16"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media-1.2.1.aar",
          "url": "media-1.2.1.aar",
          "size": 319167,
          "sha512": "e1e4a99b161b894472ba3c7d173ea6d365f3c8d5c706a5a059a374703342e3878fbc4b4f764677d1aff15d3963902dd3194b336e8f2b0e4c60b81c7e92169055",
          "sha256": "e8726018fc4c486d79f33a5cf3c6cc8cfebbe64fef4396fc2743c20235b8118f",
          "sha1": "0f71815550fb7420ce2297d7115cea5310e70d8a",
          "md5": "f29a161718328c9ed03c575085e12a16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media-1.2.1-sources.jar",
          "url": "media-1.2.1-sources.jar",
          "size": 137938,
          "sha512": "3bed030bdeb04c15086889e749953850ecb12c80f6e8bfb7d06ca75c7b9b683d854082b0b0b314d9a9bc09d9d213c6af7d9b898570c695ed11d0c507aab411ee",
          "sha256": "a9dfc4d917869dacfb72e6b81b0322231a7fdaf06e508630c055ca6c68a28cd5",
          "sha1": "700989e6ec7285ab812345aadf398f9cab35f183",
          "md5": "5746d5ac9bca50242f2c386730ba6472"
        }
      ]
    }
  ]
}
