{
  "formatVersion": "1.1",
  "component": {
    "group": "com.airbnb.android",
    "module": "lottie",
    "version": "5.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lottie-5.1.1.aar",
          "url": "lottie-5.1.1.aar",
          "size": 392955,
          "sha512": "dd2489f8da5f640ca0d16b1fad93b392bf157da89fb6311defed0188e92d1d9728353fa96189029cdeda179e42dac0485a8fb3d1c1c14f01967de524f97ecbc8",
          "sha256": "6a466c1fd8cb6db848e42e8abdbc8217b7edab2cfa2ca512630cddade94dff26",
          "sha1": "c11bef74d93c006b80fddda5b7beecec52b22d90",
          "md5": "83615673bd28328a202755af3434e2f7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "1.17.4"
          }
        }
      ],
      "files": [
        {
          "name": "lottie-5.1.1.aar",
          "url": "lottie-5.1.1.aar",
          "size": 392955,
          "sha512": "dd2489f8da5f640ca0d16b1fad93b392bf157da89fb6311defed0188e92d1d9728353fa96189029cdeda179e42dac0485a8fb3d1c1c14f01967de524f97ecbc8",
          "sha256": "6a466c1fd8cb6db848e42e8abdbc8217b7edab2cfa2ca512630cddade94dff26",
          "sha1": "c11bef74d93c006b80fddda5b7beecec52b22d90",
          "md5": "83615673bd28328a202755af3434e2f7"
        }
      ]
    }
  ]
}
