{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-android",
    "version": "1.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xt6ws6s5kffb5gn4f5ktpx2rkm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-android-1.3.9.jar",
          "url": "kotlinx-coroutines-android-1.3.9.jar",
          "size": 20118,
          "sha512": "f16537004caf9da7f5d44d89ef993af1df6392025a162f676eb60a543d876ee199f00e7ba1e2ede39c6ccbd13544a55da8403e4e37ea9e14620d7ee2fb4feb0e",
          "sha256": "3b6529d1872a2c689b2231cf3e75476badd5c5a430206c2c1967e4deb171e50d",
          "sha1": "df17db5e329363c4e9cc7bf5b661ce3723a3e460",
          "md5": "4e2d5f6f7bc380514c2a399bbf79080a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-android-1.3.9.jar",
          "url": "kotlinx-coroutines-android-1.3.9.jar",
          "size": 20118,
          "sha512": "f16537004caf9da7f5d44d89ef993af1df6392025a162f676eb60a543d876ee199f00e7ba1e2ede39c6ccbd13544a55da8403e4e37ea9e14620d7ee2fb4feb0e",
          "sha256": "3b6529d1872a2c689b2231cf3e75476badd5c5a430206c2c1967e4deb171e50d",
          "sha1": "df17db5e329363c4e9cc7bf5b661ce3723a3e460",
          "md5": "4e2d5f6f7bc380514c2a399bbf79080a"
        }
      ]
    }
  ]
}
